name: Deploy via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build Project
        run: |
          npm install
          npm run build

      - name: Deploy to cPanel
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 198.187.31.203 
          username: sigmolabs    
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 21098
          debug: true
          script: |
            cd /home/sigmolabs/invoicely-backend
            git pull origin main
            # Activate Node environment and update
            source /home/sigmolabs/nodevenv/invoicely-backend/20/bin/activate
            npm install --production
            touch tmp/restart.txt